{{- if and .Values.backend.enabled .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datagerry.fullname" . }}-backend-secret
  labels:
    {{- include "datagerry.labels" . | nindent 4 }}
type: Opaque
stringData:
  DG_RSA_PUBLIC_KEY: {{ .Values.secrets.rsaPublicKey | quote }}
  DG_RSA_PRIVATE_KEY: {{ .Values.secrets.rsaPrivateKey | quote }}
  DG_SYMMETRIC_KEY: {{ .Values.secrets.symmetricKey | quote }}
{{- end }}
